// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web. '
            'Run the FlutterFire CLI again to configure.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtf_rzOeoXps9_7zNgzIY8Ur2pKK-TTTs',
    appId: '1:131838678618:android:92f24c1a6e6ef8c265ea63',
    messagingSenderId: '131838678618',
    projectId: 'volunteer-connect-1c099',
    storageBucket: 'volunteer-connect-1c099.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgNA8b9iGa9kaNjIFwA7l6EEU2JCReV-4',
    appId: '1:131838678618:ios:87c6b1d30bc32c1c65ea63',
    messagingSenderId: '131838678618',
    projectId: 'volunteer-connect-1c099',
    storageBucket: 'volunteer-connect-1c099.firebasestorage.app',
    iosBundleId: 'com.example.volunteerConnectPlatform',
  );

}